classes = ['Automation Testing',
    'Blockchain',
    'Business Analyst',
    'Civil Engineer',
    'Data Science',
    'Database',
    'DevOps Engineer',
    'DotNet Developer',
    'ETL Developer',
    'Electrical Engineering',
    'Hadoop',
    'Health and fitness',
    'Java Developer',
    'Mechanical Engineer',
    'Network Security Engineer',
    'Operations Manager',
    'Python Developer',
    'SAP Developer',
    'Sales',
    'Testing',
    'Web Designing'
]